### ISSUE TITLE
difference in the hash

### ISSUE THREAD

**Issue by FrangaL** [matejcik/fastsum#2]
Could you explain to me why it has this difference in the hash?

fastsum test.img.xz 

6674f127532a28ec1436c2b87b0cf32083fd36441942725e5848d0534d41bc3b  test.img.xz

sha256sum test.img.xz 

e4cc7cf7f2dd4da70c4558f13047c1f4bc8398f96b549ebe31ea30e7dc3fef28  test.img.xz

**Comment by matejcik** [comment]
fastsum is not supposed to have identical output to sha256sum.

see this explanation: https://github.com/matejcik/fastsum/issues/1#issuecomment-508745745
